/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as FundsRouteImport } from './routes/funds'
import { Route as GrowRouteImport } from './routes/grow'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as YearRouteImport } from './routes/year'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowRoute = GrowRouteImport.update({
  id: '/grow',
  path: '/grow',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const YearRoute = YearRouteImport.update({
  id: '/year',
  path: '/year',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/confirm': typeof ConfirmRoute
  '/funds': typeof FundsRoute
  '/grow': typeof GrowRoute
  '/import': typeof ImportRoute
  '/imports': typeof ImportsRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/year': typeof YearRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/confirm': typeof ConfirmRoute
  '/funds': typeof FundsRoute
  '/grow': typeof GrowRoute
  '/import': typeof ImportRoute
  '/imports': typeof ImportsRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/year': typeof YearRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/confirm': typeof ConfirmRoute
  '/funds': typeof FundsRoute
  '/grow': typeof GrowRoute
  '/import': typeof ImportRoute
  '/imports': typeof ImportsRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/year': typeof YearRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/confirm'
    | '/funds'
    | '/grow'
    | '/import'
    | '/imports'
    | '/login'
    | '/reset'
    | '/rules'
    | '/settings'
    | '/year'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget'
    | '/confirm'
    | '/funds'
    | '/grow'
    | '/import'
    | '/imports'
    | '/login'
    | '/reset'
    | '/rules'
    | '/settings'
    | '/year'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/confirm'
    | '/funds'
    | '/grow'
    | '/import'
    | '/imports'
    | '/login'
    | '/reset'
    | '/rules'
    | '/settings'
    | '/year'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRoute
  ConfirmRoute: typeof ConfirmRoute
  FundsRoute: typeof FundsRoute
  GrowRoute: typeof GrowRoute
  ImportRoute: typeof ImportRoute
  ImportsRoute: typeof ImportsRoute
  LoginRoute: typeof LoginRoute
  ResetRoute: typeof ResetRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  YearRoute: typeof YearRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds': {
      id: '/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grow': {
      id: '/grow'
      path: '/grow'
      fullPath: '/grow'
      preLoaderRoute: typeof GrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/year': {
      id: '/year'
      path: '/year'
      fullPath: '/year'
      preLoaderRoute: typeof YearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRoute,
  ConfirmRoute: ConfirmRoute,
  FundsRoute: FundsRoute,
  GrowRoute: GrowRoute,
  ImportRoute: ImportRoute,
  ImportsRoute: ImportsRoute,
  LoginRoute: LoginRoute,
  ResetRoute: ResetRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  YearRoute: YearRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
