/** Deterministic keyword → category slug. Longer / more specific entries win. No models. No personal names. */
export type KeywordRule = { pattern: string; slug: string };

export const KEYWORD_RULES: KeywordRule[] = [
  { pattern: "DIR DEP", slug: "paycheck" },
  { pattern: "DIRECT DEP", slug: "paycheck" },
  { pattern: "DIRECT DEPOSIT", slug: "paycheck" },
  { pattern: "PAYROLL", slug: "paycheck" },
  { pattern: "SALARY", slug: "paycheck" },
  { pattern: "ADP ", slug: "paycheck" },
  { pattern: "GUSTO", slug: "paycheck" },
  { pattern: "WORKDAY", slug: "paycheck" },
  { pattern: "PAYCHEX", slug: "paycheck" },
  { pattern: "JUSTWORKS", slug: "paycheck" },
  { pattern: "RIPPLING", slug: "paycheck" },
  { pattern: "INTUIT PAYROLL", slug: "paycheck" },
  { pattern: "PAYLOCITY", slug: "paycheck" },
  { pattern: "DAYFORCE", slug: "paycheck" },
  { pattern: "CITY OF GLENDALE", slug: "paycheck" },
  { pattern: "NORTH HILLS CONS", slug: "paycheck" },

  { pattern: "STRIPE", slug: "side-work" },
  { pattern: "SQUARE", slug: "side-work" },
  { pattern: "ETSY", slug: "side-work" },
  { pattern: "SHOPIFY", slug: "side-work" },
  { pattern: "UBER DRIVER", slug: "side-work" },
  { pattern: "DOORDASH DASHER", slug: "side-work" },

  { pattern: "ZELLE PAYMENT FROM", slug: "other-income" },
  { pattern: "ZELLE FROM", slug: "other-income" },
  { pattern: "VENMO FROM", slug: "other-income" },
  { pattern: "CASH APP FROM", slug: "other-income" },
  { pattern: "PAYPAL INST XFER", slug: "other-income" },
  { pattern: "REMOTE ONLINE DEPOSIT", slug: "other-income" },
  { pattern: "MOBILE DEPOSIT", slug: "other-income" },
  { pattern: "APPLE CASH", slug: "other-income" },

  { pattern: "PAYMENT TO CHASE CARD", slug: "transfers-out" },
  { pattern: "PAYMENT TO CREDIT CARD", slug: "transfers-out" },
  { pattern: "CHASE CREDIT CRD", slug: "transfers-out" },

  { pattern: "RAISING CANE", slug: "dining" },
  { pattern: "SONIC DRIVE", slug: "dining" },
  { pattern: "JACK IN THE BOX", slug: "dining" },
  { pattern: "CHILI'S", slug: "dining" },
  { pattern: "APPLEBEES", slug: "dining" },
  { pattern: "CRACKER BARREL", slug: "dining" },

  { pattern: "DOLLAR GENERAL", slug: "personal" },
  { pattern: "FAMILY DOLLAR", slug: "personal" },
  { pattern: "NORDSTROM", slug: "personal" },
  { pattern: "OLD NAVY", slug: "personal" },
  { pattern: "MARSHALLS", slug: "personal" },
  { pattern: "ROSS STORES", slug: "personal" },
  { pattern: "BURLINGTON", slug: "personal" },
  { pattern: "KOHL'S", slug: "personal" },

  { pattern: "SMART AND FINAL", slug: "food" },
  { pattern: "H MART", slug: "food" },
  { pattern: "99 RANCH", slug: "food" },

  { pattern: "APS ELECTRIC", slug: "utilities" },
  { pattern: "PG&E", slug: "utilities" },
  { pattern: "PGE ", slug: "utilities" },
  { pattern: "CON EDISON", slug: "utilities" },
  { pattern: "DUKE ENERGY", slug: "utilities" },
  { pattern: "VENMO PAYMENT", slug: "transfers-out" },
  { pattern: "VENMO TO", slug: "transfers-out" },
  { pattern: "CASH APP TO", slug: "transfers-out" },

  { pattern: "IRS TREAS", slug: "other-income" },
  { pattern: "TAX REF", slug: "other-income" },
  { pattern: "INTEREST PAYMENT", slug: "other-income" },
  { pattern: "DIVIDEND", slug: "other-income" },

  { pattern: "COSTCO GAS", slug: "gas" },
  { pattern: "SAMS CLUB GAS", slug: "gas" },
  { pattern: "SHELL", slug: "gas" },
  { pattern: "CHEVRON", slug: "gas" },
  { pattern: "EXXON", slug: "gas" },
  { pattern: "MOBIL", slug: "gas" },
  { pattern: "CIRCLE K", slug: "gas" },
  { pattern: "CIRCLEK", slug: "gas" },
  { pattern: "QUIKTRIP", slug: "gas" },
  { pattern: "QT ", slug: "gas" },
  { pattern: "7-ELEVEN", slug: "gas" },
  { pattern: "7 ELEVEN", slug: "gas" },
  { pattern: "WAWA", slug: "gas" },
  { pattern: "ARCO", slug: "gas" },
  { pattern: "SINCLAIR", slug: "gas" },
  { pattern: "BP ", slug: "gas" },
  { pattern: "MAVERIK", slug: "gas" },
  { pattern: "SPEEDWAY", slug: "gas" },
  { pattern: "VALERO", slug: "gas" },
  { pattern: "MARATHON", slug: "gas" },
  { pattern: "SUNOCO", slug: "gas" },
  { pattern: "CASEYS", slug: "gas" },
  { pattern: "RACETRAC", slug: "gas" },
  { pattern: "PILOT ", slug: "gas" },
  { pattern: "LOVES ", slug: "gas" },

  { pattern: "DMV", slug: "transport" },
  { pattern: "MVD", slug: "transport" },
  { pattern: "PARKING", slug: "transport" },
  { pattern: "UBER", slug: "transport" },
  { pattern: "LYFT", slug: "transport" },
  { pattern: "TRANSIT", slug: "transport" },
  { pattern: "METRO", slug: "transport" },
  { pattern: "GEICO", slug: "transport" },
  { pattern: "STATE FARM", slug: "transport" },
  { pattern: "PROGRESSIVE", slug: "transport" },
  { pattern: "ALLSTATE", slug: "transport" },
  { pattern: "USAA", slug: "transport" },
  { pattern: "LIBERTY MUTUAL", slug: "transport" },
  { pattern: "AUTOZONE", slug: "transport" },
  { pattern: "OREILLY", slug: "transport" },
  { pattern: "O REILLY", slug: "transport" },
  { pattern: "NAPA", slug: "transport" },
  { pattern: "DISCOUNT TIRE", slug: "transport" },
  { pattern: "JIFFY LUBE", slug: "transport" },
  { pattern: "TOLL ", slug: "transport" },
  { pattern: "EZPASS", slug: "transport" },
  { pattern: "SUNPASS", slug: "transport" },

  { pattern: "UBER EATS", slug: "dining" },
  { pattern: "DOORDASH", slug: "dining" },
  { pattern: "GRUBHUB", slug: "dining" },
  { pattern: "MCDONALD", slug: "dining" },
  { pattern: "ARBY", slug: "dining" },
  { pattern: "IN-N-OUT", slug: "dining" },
  { pattern: "IN N OUT", slug: "dining" },
  { pattern: "CHIPOTLE", slug: "dining" },
  { pattern: "TACO BELL", slug: "dining" },
  { pattern: "CHICK-FIL", slug: "dining" },
  { pattern: "CHICK FIL", slug: "dining" },
  { pattern: "JERSEY MIKE", slug: "dining" },
  { pattern: "DAIRY QUEEN", slug: "dining" },
  { pattern: "PANDA EXPRESS", slug: "dining" },
  { pattern: "STARBUCKS", slug: "dining" },
  { pattern: "DUTCH BROS", slug: "dining" },
  { pattern: "DUNKIN", slug: "dining" },
  { pattern: "PANERA", slug: "dining" },
  { pattern: "WENDY", slug: "dining" },
  { pattern: "BURGER KING", slug: "dining" },
  { pattern: "POPEYES", slug: "dining" },
  { pattern: "SUBWAY", slug: "dining" },
  { pattern: "DOMINOS", slug: "dining" },
  { pattern: "PIZZA HUT", slug: "dining" },
  { pattern: "FIVE GUYS", slug: "dining" },
  { pattern: "SHAKE SHACK", slug: "dining" },
  { pattern: "WINGSTOP", slug: "dining" },
  { pattern: "WHATABURGER", slug: "dining" },
  { pattern: "KFC", slug: "dining" },
  { pattern: "PAPA JOHN", slug: "dining" },
  { pattern: "LITTLE CAESAR", slug: "dining" },
  { pattern: "SWEETGREEN", slug: "dining" },
  { pattern: "QDOBA", slug: "dining" },
  { pattern: "OLIVE GARDEN", slug: "dining" },
  { pattern: "IHOP", slug: "dining" },
  { pattern: "KRISPY KREME", slug: "dining" },
  { pattern: "CAFE ", slug: "dining" },
  { pattern: "VENDING", slug: "dining" },

  { pattern: "TRADER JOE", slug: "food" },
  { pattern: "WHOLE FOODS", slug: "food" },
  { pattern: "KROGER", slug: "food" },
  { pattern: "FRYS", slug: "food" },
  { pattern: "FRY'S", slug: "food" },
  { pattern: "SAFEWAY", slug: "food" },
  { pattern: "ALBERTSONS", slug: "food" },
  { pattern: "PUBLIX", slug: "food" },
  { pattern: "HEB", slug: "food" },
  { pattern: "H-E-B", slug: "food" },
  { pattern: "ALDI", slug: "food" },
  { pattern: "LIDL", slug: "food" },
  { pattern: "MEIJER", slug: "food" },
  { pattern: "WEGMANS", slug: "food" },
  { pattern: "WINCO", slug: "food" },
  { pattern: "SPROUTS", slug: "food" },
  { pattern: "FOOD LION", slug: "food" },
  { pattern: "STOP & SHOP", slug: "food" },
  { pattern: "GIANT ", slug: "food" },
  { pattern: "WALMART", slug: "food" },
  { pattern: "WM SUPERCENTER", slug: "food" },
  { pattern: "COSTCO", slug: "food" },
  { pattern: "SAMS CLUB", slug: "food" },
  { pattern: "GROCERY", slug: "food" },
  { pattern: "INSTACART", slug: "food" },
  { pattern: "VONS", slug: "food" },
  { pattern: "HARRIS TEETER", slug: "food" },
  { pattern: "FOOD 4 LESS", slug: "food" },

  { pattern: "PROPERTY MGMT", slug: "housing" },
  { pattern: "PROPERTY MANAGEMENT", slug: "housing" },
  { pattern: "RENT", slug: "housing" },
  { pattern: "APARTMENT", slug: "housing" },
  { pattern: "MORTGAGE", slug: "housing" },
  { pattern: "HOA ", slug: "housing" },
  { pattern: "PROPERTY TAX", slug: "housing" },
  { pattern: "LANDLORD", slug: "housing" },
  { pattern: "ZILLOW RENT", slug: "housing" },
  { pattern: "APARTMENTS.COM", slug: "housing" },

  { pattern: "ELECTRIC", slug: "utilities" },
  { pattern: "POWER ", slug: "utilities" },
  { pattern: "WATER", slug: "utilities" },
  { pattern: "GAS CO", slug: "utilities" },
  { pattern: "INTERNET", slug: "utilities" },
  { pattern: "COMCAST", slug: "utilities" },
  { pattern: "XFINITY", slug: "utilities" },
  { pattern: "COX ", slug: "utilities" },
  { pattern: "AT&T", slug: "utilities" },
  { pattern: "VERIZON", slug: "utilities" },
  { pattern: "T-MOBILE", slug: "utilities" },
  { pattern: "TMOBILE", slug: "utilities" },
  { pattern: "SPECTRUM", slug: "utilities" },
  { pattern: "TRASH", slug: "utilities" },
  { pattern: "WASTE MGMT", slug: "utilities" },

  { pattern: "CVS", slug: "health" },
  { pattern: "WALGREENS", slug: "health" },
  { pattern: "RITE AID", slug: "health" },
  { pattern: "PHARMACY", slug: "health" },
  { pattern: "DENTAL", slug: "health" },
  { pattern: "HOSPITAL", slug: "health" },
  { pattern: "CLINIC", slug: "health" },
  { pattern: "URGENT CARE", slug: "health" },
  { pattern: "DOCTOR", slug: "health" },
  { pattern: "PHYSICIAN", slug: "health" },
  { pattern: "KAISER", slug: "health" },
  { pattern: "PLANET FITNESS", slug: "health" },
  { pattern: "LA FITNESS", slug: "health" },
  { pattern: "PELOTON", slug: "health" },

  { pattern: "NETFLIX", slug: "subscriptions" },
  { pattern: "SPOTIFY", slug: "subscriptions" },
  { pattern: "DISNEY", slug: "subscriptions" },
  { pattern: "HULU", slug: "subscriptions" },
  { pattern: "HBO", slug: "subscriptions" },
  { pattern: "MAX.COM", slug: "subscriptions" },
  { pattern: "APPLE.COM/BILL", slug: "subscriptions" },
  { pattern: "ICLOUD", slug: "subscriptions" },
  { pattern: "YOUTUBE PREMIUM", slug: "subscriptions" },
  { pattern: "AMAZON PRIME", slug: "subscriptions" },
  { pattern: "ADOBE", slug: "subscriptions" },
  { pattern: "MICROSOFT 365", slug: "subscriptions" },
  { pattern: "GOOGLE ONE", slug: "subscriptions" },
  { pattern: "PARAMOUNT", slug: "subscriptions" },
  { pattern: "PEACOCK", slug: "subscriptions" },
  { pattern: "AUDIBLE", slug: "subscriptions" },
  { pattern: "CHATGPT", slug: "subscriptions" },

  { pattern: "SEATGEEK", slug: "entertainment" },
  { pattern: "TICKETMASTER", slug: "entertainment" },
  { pattern: "STUBHUB", slug: "entertainment" },
  { pattern: "AMC ", slug: "entertainment" },
  { pattern: "REGAL", slug: "entertainment" },
  { pattern: "CINEMARK", slug: "entertainment" },
  { pattern: "XBOX", slug: "entertainment" },
  { pattern: "PLAYSTATION", slug: "entertainment" },
  { pattern: "STEAM", slug: "entertainment" },
  { pattern: "NINTENDO", slug: "entertainment" },
  { pattern: "BOWLING", slug: "entertainment" },

  { pattern: "CHURCH", slug: "giving" },
  { pattern: "TITHE", slug: "giving" },
  { pattern: "DONATION", slug: "giving" },
  { pattern: "GOFUNDME", slug: "giving" },
  { pattern: "PATREON", slug: "giving" },

  { pattern: "AMAZON", slug: "personal" },
  { pattern: "AMZN", slug: "personal" },
  { pattern: "TARGET", slug: "personal" },
  { pattern: "DICKS SPORTING", slug: "personal" },
  { pattern: "NIKE", slug: "personal" },
  { pattern: "HOME DEPOT", slug: "personal" },
  { pattern: "LOWES", slug: "personal" },
  { pattern: "LOWE'S", slug: "personal" },
  { pattern: "IKEA", slug: "personal" },
  { pattern: "BARBER", slug: "personal" },
  { pattern: "HAIRCUT", slug: "personal" },
  { pattern: "SALON", slug: "personal" },
  { pattern: "GREAT CLIPS", slug: "personal" },
  { pattern: "SUPERCUTS", slug: "personal" },
  { pattern: "LAUNDRY", slug: "personal" },
  { pattern: "BEST BUY", slug: "personal" },
  { pattern: "APPLE.COM", slug: "personal" },
  { pattern: "ULTA", slug: "personal" },
  { pattern: "SEPHORA", slug: "personal" },
  { pattern: "TJ MAXX", slug: "personal" },
  { pattern: "DOLLAR TREE", slug: "personal" },

  { pattern: "CHEWY", slug: "pets" },
  { pattern: "PETCO", slug: "pets" },
  { pattern: "PETSMART", slug: "pets" },
  { pattern: "VET ", slug: "pets" },
  { pattern: "VETERINAR", slug: "pets" },

  { pattern: "AIRBNB", slug: "travel" },
  { pattern: "VRBO", slug: "travel" },
  { pattern: "MARRIOTT", slug: "travel" },
  { pattern: "HILTON", slug: "travel" },
  { pattern: "HYATT", slug: "travel" },
  { pattern: "SOUTHWEST", slug: "travel" },
  { pattern: "DELTA AIR", slug: "travel" },
  { pattern: "UNITED AIR", slug: "travel" },
  { pattern: "AMERICAN AIR", slug: "travel" },
  { pattern: "JETBLUE", slug: "travel" },
  { pattern: "AIRLINE", slug: "travel" },
  { pattern: "EXPEDIA", slug: "travel" },
  { pattern: "ALASKA AIR", slug: "travel" },
  { pattern: "FRONTIER AIR", slug: "travel" },
  { pattern: "BOOKING.COM", slug: "travel" },

  { pattern: "TUITION", slug: "education" },
  { pattern: "UNIVERSITY", slug: "education" },
  { pattern: "COLLEGE", slug: "education" },
  { pattern: "TEXTBOOK", slug: "education" },
  { pattern: "CHEGG", slug: "education" },
  { pattern: "COURSERA", slug: "education" },
  { pattern: "Udemy", slug: "education" },

  { pattern: "DAYCARE", slug: "childcare" },
  { pattern: "CHILD CARE", slug: "childcare" },
  { pattern: "BABYSIT", slug: "childcare" },
  { pattern: "KINDERCARE", slug: "childcare" },

  { pattern: "NAVIENT", slug: "debt" },
  { pattern: "MOHELA", slug: "debt" },
  { pattern: "STUDENT LOAN", slug: "debt" },
  { pattern: "LOAN PAYMENT", slug: "debt" },
  { pattern: "CREDIT CARD PAYMENT", slug: "debt" },
  { pattern: "AFFIRM", slug: "debt" },
  { pattern: "KLARNA", slug: "debt" },
  { pattern: "AFTERPAY", slug: "debt" },
  { pattern: "SOFI", slug: "debt" },
];

const SORTED = [...KEYWORD_RULES].sort((a, b) => b.pattern.length - a.pattern.length);

export function matchKeyword(text: string): { slug: string; pattern: string } | null {
  const hay = ` ${String(text || "").toUpperCase()} `;
  for (const rule of SORTED) {
    if (hay.includes(rule.pattern.toUpperCase())) return { slug: rule.slug, pattern: rule.pattern };
  }
  return null;
}

export function matchKeywordSlug(text: string): string | null {
  return matchKeyword(text)?.slug ?? null;
}

export const SLUG_FALLBACKS: Record<string, string[]> = {
  dining: ["food"],
  subscriptions: ["entertainment", "personal"],
  pets: ["personal"],
  travel: ["entertainment", "other"],
  "transfers-out": ["other"],
  groceries: ["food"],
};
