/** Deterministic keyword → category slug. Longer / more specific entries win. No models. No personal names. */
export type KeywordRule = { pattern: string; slug: string; weak?: boolean };

export const KEYWORD_RULES: KeywordRule[] = [
  { pattern: "DIR DEP", slug: "paycheck" },
  { pattern: "DIRECT DEP", slug: "paycheck" },
  { pattern: "DIRECT DEPOSIT", slug: "paycheck" },
  { pattern: "PAYROLL", slug: "paycheck" },
  { pattern: "SALARY", slug: "paycheck" },
  { pattern: "ADP ", slug: "paycheck" },
  { pattern: "GUSTO", slug: "paycheck" },
  { pattern: "WORKDAY", slug: "paycheck" },
  { pattern: "PAYCHEX", slug: "paycheck" },
  { pattern: "JUSTWORKS", slug: "paycheck" },
  { pattern: "RIPPLING", slug: "paycheck" },
  { pattern: "INTUIT PAYROLL", slug: "paycheck" },
  { pattern: "PAYLOCITY", slug: "paycheck" },
  { pattern: "DAYFORCE", slug: "paycheck" },

  { pattern: "STRIPE", slug: "side-work" },
  { pattern: "SQUARE", slug: "side-work" },
  { pattern: "ETSY", slug: "side-work" },
  { pattern: "SHOPIFY", slug: "side-work" },
  { pattern: "UBER DRIVER", slug: "side-work" },
  { pattern: "DOORDASH DASHER", slug: "side-work" },

  { pattern: "ZELLE PAYMENT FROM", slug: "other-income" },
  { pattern: "ZELLE FROM", slug: "other-income" },
  { pattern: "VENMO FROM", slug: "other-income" },
  { pattern: "CASH APP FROM", slug: "other-income" },
  { pattern: "PAYPAL INST XFER", slug: "other-income" },
  { pattern: "REMOTE ONLINE DEPOSIT", slug: "other-income" },
  { pattern: "MOBILE DEPOSIT", slug: "other-income" },
  { pattern: "APPLE CASH", slug: "other-income" },

  { pattern: "PAYMENT TO CHASE CARD", slug: "transfers-out" },
  { pattern: "PAYMENT TO CREDIT CARD", slug: "transfers-out" },
  { pattern: "CHASE CREDIT CRD", slug: "transfers-out" },

  { pattern: "RAISING CANE", slug: "dining" },
  { pattern: "SONIC DRIVE", slug: "dining" },
  { pattern: "JACK IN THE BOX", slug: "dining" },
  { pattern: "CHILI'S", slug: "dining" },
  { pattern: "APPLEBEES", slug: "dining" },
  { pattern: "CRACKER BARREL", slug: "dining" },

  { pattern: "DOLLAR GENERAL", slug: "personal" },
  { pattern: "FAMILY DOLLAR", slug: "personal" },
  { pattern: "NORDSTROM", slug: "personal" },
  { pattern: "OLD NAVY", slug: "personal" },
  { pattern: "MARSHALLS", slug: "personal" },
  { pattern: "ROSS STORES", slug: "personal" },
  { pattern: "BURLINGTON", slug: "personal" },
  { pattern: "KOHL'S", slug: "personal" },

  { pattern: "SMART AND FINAL", slug: "food" },
  { pattern: "H MART", slug: "food" },
  { pattern: "99 RANCH", slug: "food" },

  { pattern: "APS ELECTRIC", slug: "utilities" },
  { pattern: "PG&E", slug: "utilities" },
  { pattern: "PGE ", slug: "utilities" },
  { pattern: "CON EDISON", slug: "utilities" },
  { pattern: "DUKE ENERGY", slug: "utilities" },
  { pattern: "VENMO PAYMENT", slug: "transfers-out" },
  { pattern: "VENMO TO", slug: "transfers-out" },
  { pattern: "CASH APP TO", slug: "transfers-out" },

  { pattern: "IRS TREAS", slug: "other-income" },
  { pattern: "TAX REF", slug: "other-income" },
  { pattern: "INTEREST PAYMENT", slug: "other-income" },
  { pattern: "DIVIDEND", slug: "other-income" },

  { pattern: "COSTCO GAS", slug: "gas" },
  { pattern: "SAMS CLUB GAS", slug: "gas" },
  { pattern: "SHELL", slug: "gas" },
  { pattern: "CHEVRON", slug: "gas" },
  { pattern: "EXXON", slug: "gas" },
  { pattern: "MOBIL", slug: "gas" },
  { pattern: "CIRCLE K", slug: "gas" },
  { pattern: "CIRCLEK", slug: "gas" },
  { pattern: "QUIKTRIP", slug: "gas" },
  { pattern: "QT ", slug: "gas" },
  { pattern: "7-ELEVEN", slug: "gas" },
  { pattern: "7 ELEVEN", slug: "gas" },
  { pattern: "WAWA", slug: "gas" },
  { pattern: "ARCO", slug: "gas" },
  { pattern: "SINCLAIR", slug: "gas" },
  { pattern: "BP ", slug: "gas" },
  { pattern: "MAVERIK", slug: "gas" },
  { pattern: "SPEEDWAY", slug: "gas" },
  { pattern: "VALERO", slug: "gas" },
  { pattern: "MARATHON", slug: "gas" },
  { pattern: "SUNOCO", slug: "gas" },
  { pattern: "CASEYS", slug: "gas" },
  { pattern: "RACETRAC", slug: "gas" },
  { pattern: "PILOT ", slug: "gas" },
  { pattern: "LOVES ", slug: "gas" },

  { pattern: "DMV", slug: "transport" },
  { pattern: "MVD", slug: "transport" },
  { pattern: "PARKING", slug: "transport" },
  { pattern: "UBER", slug: "transport" },
  { pattern: "LYFT", slug: "transport" },
  { pattern: "TRANSIT", slug: "transport" },
  { pattern: "METRO", slug: "transport" },
  { pattern: "GEICO", slug: "transport" },
  { pattern: "STATE FARM", slug: "transport" },
  { pattern: "PROGRESSIVE", slug: "transport" },
  { pattern: "ALLSTATE", slug: "transport" },
  { pattern: "USAA", slug: "transport" },
  { pattern: "LIBERTY MUTUAL", slug: "transport" },
  { pattern: "AUTOZONE", slug: "transport" },
  { pattern: "OREILLY", slug: "transport" },
  { pattern: "O REILLY", slug: "transport" },
  { pattern: "NAPA", slug: "transport" },
  { pattern: "DISCOUNT TIRE", slug: "transport" },
  { pattern: "JIFFY LUBE", slug: "transport" },
  { pattern: "TOLL ", slug: "transport" },
  { pattern: "EZPASS", slug: "transport" },
  { pattern: "SUNPASS", slug: "transport" },

  { pattern: "UBER EATS", slug: "dining" },
  { pattern: "DOORDASH", slug: "dining" },
  { pattern: "GRUBHUB", slug: "dining" },
  { pattern: "MCDONALD", slug: "dining" },
  { pattern: "ARBY", slug: "dining" },
  { pattern: "IN-N-OUT", slug: "dining" },
  { pattern: "IN N OUT", slug: "dining" },
  { pattern: "CHIPOTLE", slug: "dining" },
  { pattern: "TACO BELL", slug: "dining" },
  { pattern: "CHICK-FIL", slug: "dining" },
  { pattern: "CHICK FIL", slug: "dining" },
  { pattern: "JERSEY MIKE", slug: "dining" },
  { pattern: "DAIRY QUEEN", slug: "dining" },
  { pattern: "PANDA EXPRESS", slug: "dining" },
  { pattern: "STARBUCKS", slug: "dining" },
  { pattern: "DUTCH BROS", slug: "dining" },
  { pattern: "DUNKIN", slug: "dining" },
  { pattern: "PANERA", slug: "dining" },
  { pattern: "WENDY", slug: "dining" },
  { pattern: "BURGER KING", slug: "dining" },
  { pattern: "POPEYES", slug: "dining" },
  { pattern: "SUBWAY", slug: "dining" },
  { pattern: "DOMINOS", slug: "dining" },
  { pattern: "PIZZA HUT", slug: "dining" },
  { pattern: "FIVE GUYS", slug: "dining" },
  { pattern: "SHAKE SHACK", slug: "dining" },
  { pattern: "WINGSTOP", slug: "dining" },
  { pattern: "WHATABURGER", slug: "dining" },
  { pattern: "KFC", slug: "dining" },
  { pattern: "PAPA JOHN", slug: "dining" },
  { pattern: "LITTLE CAESAR", slug: "dining" },
  { pattern: "SWEETGREEN", slug: "dining" },
  { pattern: "QDOBA", slug: "dining" },
  { pattern: "OLIVE GARDEN", slug: "dining" },
  { pattern: "IHOP", slug: "dining" },
  { pattern: "KRISPY KREME", slug: "dining" },
  { pattern: "CAFE ", slug: "dining" },
  { pattern: "VENDING", slug: "dining" },

  { pattern: "TRADER JOE", slug: "food" },
  { pattern: "WHOLE FOODS", slug: "food" },
  { pattern: "KROGER", slug: "food" },
  { pattern: "FRYS", slug: "food" },
  { pattern: "FRY'S", slug: "food" },
  { pattern: "SAFEWAY", slug: "food" },
  { pattern: "ALBERTSONS", slug: "food" },
  { pattern: "PUBLIX", slug: "food" },
  { pattern: "HEB", slug: "food" },
  { pattern: "H-E-B", slug: "food" },
  { pattern: "ALDI", slug: "food" },
  { pattern: "LIDL", slug: "food" },
  { pattern: "MEIJER", slug: "food" },
  { pattern: "WEGMANS", slug: "food" },
  { pattern: "WINCO", slug: "food" },
  { pattern: "SPROUTS", slug: "food" },
  { pattern: "FOOD LION", slug: "food" },
  { pattern: "STOP & SHOP", slug: "food" },
  { pattern: "GIANT ", slug: "food" },
  { pattern: "WALMART", slug: "food", weak: true },
  { pattern: "WM SUPERCENTER", slug: "food", weak: true },
  { pattern: "COSTCO", slug: "food", weak: true },
  { pattern: "SAMS CLUB", slug: "food", weak: true },
  { pattern: "GROCERY", slug: "food" },
  { pattern: "INSTACART", slug: "food" },
  { pattern: "VONS", slug: "food" },
  { pattern: "HARRIS TEETER", slug: "food" },
  { pattern: "FOOD 4 LESS", slug: "food" },

  { pattern: "PROPERTY MGMT", slug: "housing" },
  { pattern: "PROPERTY MANAGEMENT", slug: "housing" },
  { pattern: "RENT", slug: "housing" },
  { pattern: "APARTMENT", slug: "housing" },
  { pattern: "MORTGAGE", slug: "housing" },
  { pattern: "HOA ", slug: "housing" },
  { pattern: "PROPERTY TAX", slug: "housing" },
  { pattern: "LANDLORD", slug: "housing" },
  { pattern: "ZILLOW RENT", slug: "housing" },
  { pattern: "APARTMENTS.COM", slug: "housing" },

  { pattern: "ELECTRIC", slug: "utilities" },
  { pattern: "POWER ", slug: "utilities" },
  { pattern: "WATER", slug: "utilities" },
  { pattern: "GAS CO", slug: "utilities" },
  { pattern: "INTERNET", slug: "utilities" },
  { pattern: "COMCAST", slug: "utilities" },
  { pattern: "XFINITY", slug: "utilities" },
  { pattern: "COX ", slug: "utilities" },
  { pattern: "AT&T", slug: "utilities" },
  { pattern: "VERIZON", slug: "utilities" },
  { pattern: "T-MOBILE", slug: "utilities" },
  { pattern: "TMOBILE", slug: "utilities" },
  { pattern: "SPECTRUM", slug: "utilities" },
  { pattern: "TRASH", slug: "utilities" },
  { pattern: "WASTE MGMT", slug: "utilities" },

  { pattern: "CVS", slug: "health" },
  { pattern: "WALGREENS", slug: "health" },
  { pattern: "RITE AID", slug: "health" },
  { pattern: "PHARMACY", slug: "health" },
  { pattern: "DENTAL", slug: "health" },
  { pattern: "HOSPITAL", slug: "health" },
  { pattern: "CLINIC", slug: "health" },
  { pattern: "URGENT CARE", slug: "health" },
  { pattern: "DOCTOR", slug: "health" },
  { pattern: "PHYSICIAN", slug: "health" },
  { pattern: "KAISER", slug: "health" },
  { pattern: "PLANET FITNESS", slug: "health" },
  { pattern: "LA FITNESS", slug: "health" },
  { pattern: "PELOTON", slug: "health" },

  { pattern: "NETFLIX", slug: "subscriptions" },
  { pattern: "STREAMBOX", slug: "subscriptions" },
  { pattern: "SPOTIFY", slug: "subscriptions" },
  { pattern: "DISNEY", slug: "subscriptions" },
  { pattern: "HULU", slug: "subscriptions" },
  { pattern: "HBO", slug: "subscriptions" },
  { pattern: "MAX.COM", slug: "subscriptions" },
  { pattern: "APPLE.COM/BILL", slug: "subscriptions" },
  { pattern: "ICLOUD", slug: "subscriptions" },
  { pattern: "YOUTUBE PREMIUM", slug: "subscriptions" },
  { pattern: "AMAZON PRIME", slug: "subscriptions" },
  { pattern: "ADOBE", slug: "subscriptions" },
  { pattern: "MICROSOFT 365", slug: "subscriptions" },
  { pattern: "GOOGLE ONE", slug: "subscriptions" },
  { pattern: "PARAMOUNT", slug: "subscriptions" },
  { pattern: "PEACOCK", slug: "subscriptions" },
  { pattern: "AUDIBLE", slug: "subscriptions" },
  { pattern: "CHATGPT", slug: "subscriptions" },

  { pattern: "SEATGEEK", slug: "entertainment" },
  { pattern: "TICKETMASTER", slug: "entertainment" },
  { pattern: "STUBHUB", slug: "entertainment" },
  { pattern: "AMC ", slug: "entertainment" },
  { pattern: "REGAL", slug: "entertainment" },
  { pattern: "CINEMARK", slug: "entertainment" },
  { pattern: "XBOX", slug: "entertainment" },
  { pattern: "PLAYSTATION", slug: "entertainment" },
  { pattern: "STEAM", slug: "entertainment" },
  { pattern: "NINTENDO", slug: "entertainment" },
  { pattern: "BOWLING", slug: "entertainment" },

  { pattern: "CHURCH", slug: "giving" },
  { pattern: "TITHE", slug: "giving" },
  { pattern: "DONATION", slug: "giving" },
  { pattern: "GOFUNDME", slug: "giving" },
  { pattern: "PATREON", slug: "giving" },

  { pattern: "AMAZON", slug: "personal", weak: true },
  { pattern: "AMZN", slug: "personal", weak: true },
  { pattern: "TARGET", slug: "personal", weak: true },
  { pattern: "DICKS SPORTING", slug: "personal" },
  { pattern: "NIKE", slug: "personal" },
  { pattern: "HOME DEPOT", slug: "personal" },
  { pattern: "LOWES", slug: "personal" },
  { pattern: "LOWE'S", slug: "personal" },
  { pattern: "IKEA", slug: "personal" },
  { pattern: "BARBER", slug: "personal" },
  { pattern: "HAIRCUT", slug: "personal" },
  { pattern: "SALON", slug: "personal" },
  { pattern: "GREAT CLIPS", slug: "personal" },
  { pattern: "SUPERCUTS", slug: "personal" },
  { pattern: "LAUNDRY", slug: "personal" },
  { pattern: "BEST BUY", slug: "personal" },
  { pattern: "APPLE.COM", slug: "personal" },
  { pattern: "ULTA", slug: "personal" },
  { pattern: "SEPHORA", slug: "personal" },
  { pattern: "TJ MAXX", slug: "personal" },
  { pattern: "DOLLAR TREE", slug: "personal" },

  { pattern: "CHEWY", slug: "pets" },
  { pattern: "PETCO", slug: "pets" },
  { pattern: "PETSMART", slug: "pets" },
  { pattern: "VET ", slug: "pets" },
  { pattern: "VETERINAR", slug: "pets" },

  { pattern: "AIRBNB", slug: "travel" },
  { pattern: "VRBO", slug: "travel" },
  { pattern: "MARRIOTT", slug: "travel" },
  { pattern: "HILTON", slug: "travel" },
  { pattern: "HYATT", slug: "travel" },
  { pattern: "SOUTHWEST", slug: "travel" },
  { pattern: "DELTA AIR", slug: "travel" },
  { pattern: "UNITED AIR", slug: "travel" },
  { pattern: "AMERICAN AIR", slug: "travel" },
  { pattern: "JETBLUE", slug: "travel" },
  { pattern: "AIRLINE", slug: "travel" },
  { pattern: "EXPEDIA", slug: "travel" },
  { pattern: "ALASKA AIR", slug: "travel" },
  { pattern: "FRONTIER AIR", slug: "travel" },
  { pattern: "BOOKING.COM", slug: "travel" },

  { pattern: "TUITION", slug: "education" },
  { pattern: "UNIVERSITY", slug: "education" },
  { pattern: "COLLEGE", slug: "education" },
  { pattern: "TEXTBOOK", slug: "education" },
  { pattern: "CHEGG", slug: "education" },
  { pattern: "COURSERA", slug: "education" },
  { pattern: "Udemy", slug: "education" },

  { pattern: "DAYCARE", slug: "childcare" },
  { pattern: "CHILD CARE", slug: "childcare" },
  { pattern: "BABYSIT", slug: "childcare" },
  { pattern: "KINDERCARE", slug: "childcare" },

  { pattern: "NAVIENT", slug: "debt" },
  { pattern: "MOHELA", slug: "debt" },
  { pattern: "STUDENT LOAN", slug: "debt" },
  { pattern: "LOAN PAYMENT", slug: "debt" },
  { pattern: "CREDIT CARD PAYMENT", slug: "debt" },
  { pattern: "AFFIRM", slug: "debt" },
  { pattern: "KLARNA", slug: "debt" },
  { pattern: "AFTERPAY", slug: "debt" },
  { pattern: "SOFI", slug: "debt" },
  { pattern: "SSA TREAS", slug: "other-income" },
  { pattern: "SOCIAL SECURITY", slug: "other-income" },
  { pattern: "UNEMPLOYMENT", slug: "other-income" },
  { pattern: "CHILD SUPPORT", slug: "other-income" },
  { pattern: "VENMO CASHOUT", slug: "other-income" },
  { pattern: "ATM FEE", slug: "other" },
  { pattern: "OVERDRAFT", slug: "other" },
  { pattern: "FOREIGN TRANSACTION", slug: "other" },
  { pattern: "SRP ", slug: "utilities" },
  { pattern: "SALT RIVER PROJECT", slug: "utilities" },
  { pattern: "APS PAYMENT", slug: "utilities" },
  { pattern: "ARIZONA PUBLIC SERVICE", slug: "utilities" },
  { pattern: "SOUTHWEST GAS", slug: "utilities" },
  { pattern: "CITY OF PHOENIX", slug: "utilities" },
  { pattern: "BASHAS", slug: "food" },
  { pattern: "AJ'S FINE", slug: "food" },
  { pattern: "FOOD CITY", slug: "food" },
  { pattern: "WHOLEFDS", slug: "food" },
  { pattern: "TRADER JOES", slug: "food" },
  { pattern: "FRYS FOOD", slug: "food" },
  { pattern: "CAVA", slug: "dining" },
  { pattern: "DEL TACO", slug: "dining" },
  { pattern: "JIMMY JOHN", slug: "dining" },
  { pattern: "FIREHOUSE SUB", slug: "dining" },
  { pattern: "CULVER", slug: "dining" },
  { pattern: "RAISING CANES", slug: "dining" },
  { pattern: "CAFE RIO", slug: "dining" },
  { pattern: "MOD PIZZA", slug: "dining" },
  { pattern: "BLAZE PIZZA", slug: "dining" },
  { pattern: "CRUNCHYROLL", slug: "subscriptions" },
  { pattern: "NYTIMES", slug: "subscriptions" },
  { pattern: "NY TIMES", slug: "subscriptions" },
  { pattern: "DROPBOX", slug: "subscriptions" },
  { pattern: "ZOOM.US", slug: "subscriptions" },
  { pattern: "OPENAI", slug: "subscriptions" },
  { pattern: "CHATGPT", slug: "subscriptions" },
  { pattern: "CLAUDE.AI", slug: "subscriptions" },
  { pattern: "ANTHROPIC", slug: "subscriptions" },
  { pattern: "CANVA", slug: "subscriptions" },
  { pattern: "NOTION", slug: "subscriptions" },
  { pattern: "GITHUB", slug: "subscriptions" },
  { pattern: "LINKEDIN", slug: "subscriptions" },
  { pattern: "YOUTUBE", slug: "subscriptions" },
  { pattern: "DISNEY PLUS", slug: "subscriptions" },
  { pattern: "DISNEY+", slug: "subscriptions" },
  { pattern: "EPIC GAMES", slug: "entertainment" },
  { pattern: "ROBLOX", slug: "entertainment" },
  { pattern: "TWITCH", slug: "entertainment" },
  { pattern: "REI ", slug: "personal" },
  { pattern: "ACADEMY SPORTS", slug: "personal" },
  { pattern: "MACY", slug: "personal" },
  { pattern: "NORDSTROM RACK", slug: "personal" },
  { pattern: "WAYFAIR", slug: "personal" },
  { pattern: "CONTAINER STORE", slug: "personal" },
  { pattern: "BANFIELD", slug: "pets" },
  { pattern: "RENTERS INS", slug: "housing" },
  { pattern: "RENTAL INS", slug: "housing" },
  { pattern: "VALLEY METRO", slug: "transport" },
  { pattern: "LIGHT RAIL", slug: "transport" },
  { pattern: "COX COMM", slug: "utilities" },
  { pattern: "CENTURYLINK", slug: "utilities" },
  { pattern: "GOOGLE FI", slug: "utilities" },
  { pattern: "FILIBERTOS", slug: "dining" },
  { pattern: "PITA JUNGLE", slug: "dining" },
  { pattern: "EEGEES", slug: "dining" },
  { pattern: "DISNEY STORE", slug: "personal" },

  { pattern: "NATIONAL GRID", slug: "utilities" },
  { pattern: "PSEG", slug: "utilities" },
  { pattern: "COMED", slug: "utilities" },
  { pattern: "XCEL ENERGY", slug: "utilities" },
  { pattern: "FLORIDA POWER", slug: "utilities" },
  { pattern: "FPL ", slug: "utilities" },
  { pattern: "ENTERGY", slug: "utilities" },
  { pattern: "DOMINION ENERGY", slug: "utilities" },
  { pattern: "EVERSOURCE", slug: "utilities" },
  { pattern: "AMEREN", slug: "utilities" },
  { pattern: "NIPSCO", slug: "utilities" },
  { pattern: "WASTE MANAGEMENT", slug: "utilities" },
  { pattern: "REPUBLIC SERVICES", slug: "utilities" },
  { pattern: "CITY WATER", slug: "utilities" },

  { pattern: "US CELLULAR", slug: "utilities" },
  { pattern: "CRICKET WIRELESS", slug: "utilities" },
  { pattern: "MINT MOBILE", slug: "utilities" },
  { pattern: "BOOST MOBILE", slug: "utilities" },
  { pattern: "CONSUMER CELLULAR", slug: "utilities" },
  { pattern: "OPTIMUM", slug: "utilities" },
  { pattern: "FRONTIER COMM", slug: "utilities" },
  { pattern: "CHARTER COMM", slug: "utilities" },

  { pattern: "FARMERS INS", slug: "transport" },
  { pattern: "NATIONWIDE INS", slug: "transport" },
  { pattern: "TRAVELERS INS", slug: "transport" },
  { pattern: "HARTFORD INS", slug: "transport" },
  { pattern: "BLUE CROSS", slug: "health" },
  { pattern: "AETNA", slug: "health" },
  { pattern: "CIGNA", slug: "health" },
  { pattern: "UNITEDHEALTH", slug: "health" },
  { pattern: "HUMANA", slug: "health" },
  { pattern: "EXPRESS SCRIPTS", slug: "health" },
  { pattern: "LABCORP", slug: "health" },
  { pattern: "QUEST DIAG", slug: "health" },
  { pattern: "DUANE READE", slug: "health" },

  { pattern: "SLING TV", slug: "subscriptions" },
  { pattern: "YOUTUBE TV", slug: "subscriptions" },
  { pattern: "APPLE TV", slug: "subscriptions" },
  { pattern: "SLACK", slug: "subscriptions" },
  { pattern: "1PASSWORD", slug: "subscriptions" },
  { pattern: "NORTON", slug: "subscriptions" },
  { pattern: "DUOLINGO", slug: "subscriptions" },

  { pattern: "PHILLIPS 66", slug: "gas" },
  { pattern: "CONOCO", slug: "gas" },
  { pattern: "TEXACO", slug: "gas" },
  { pattern: "SHEETZ", slug: "gas" },
  { pattern: "KUM & GO", slug: "gas" },
  { pattern: "GETGO", slug: "gas" },
  { pattern: "BUCCEE", slug: "gas" },

  { pattern: "SHOPRITE", slug: "food" },
  { pattern: "PIGGLY WIGGLY", slug: "food" },
  { pattern: "WINN DIXIE", slug: "food" },
  { pattern: "RALPHS", slug: "food" },
  { pattern: "JEWEL OSCO", slug: "food" },
  { pattern: "HY-VEE", slug: "food" },
  { pattern: "HY VEE", slug: "food" },
  { pattern: "FRED MEYER", slug: "food" },
  { pattern: "GIANT EAGLE", slug: "food" },
  { pattern: "PRICE CHOPPER", slug: "food" },
  { pattern: "MARKET BASKET", slug: "food" },
  { pattern: "BJS WHOLESALE", slug: "food", weak: true },
  { pattern: "BJ'S", slug: "food", weak: true },
  { pattern: "EBAY", slug: "personal", weak: true },

  { pattern: "OUTBACK", slug: "dining" },
  { pattern: "RED LOBSTER", slug: "dining" },
  { pattern: "BUFFALO WILD", slug: "dining" },
  { pattern: "EL POLLO", slug: "dining" },
  { pattern: "POTBELLY", slug: "dining" },
  { pattern: "NOODLES & CO", slug: "dining" },
  { pattern: "PORTILLO", slug: "dining" },

  { pattern: "FASTRAK", slug: "transport" },
  { pattern: "IPASS", slug: "transport" },
  { pattern: "PEACH PASS", slug: "transport" },
  { pattern: "TXTAG", slug: "transport" },

  { pattern: "POWERSCHOOL", slug: "education" },
  { pattern: "SCHOOL DISTRICT", slug: "education" },
  { pattern: "SCHOLASTIC", slug: "education" },
  { pattern: "FOLLETT", slug: "education" },

  { pattern: "MONTHLY SERVICE FEE", slug: "other" },
  { pattern: "SERVICE FEE", slug: "other" },
  { pattern: "NSF FEE", slug: "other" },
  { pattern: "WIRE FEE", slug: "other" },
  { pattern: "PAPER STATEMENT", slug: "other" },
  { pattern: "KING SOOPERS", slug: "food" },
  { pattern: "SMITHS FOOD", slug: "food" },
  { pattern: "STATER BROS", slug: "food" },
  { pattern: "INGLES MARKET", slug: "food" },
  { pattern: "BI-LO", slug: "food" },
  { pattern: "SAVE A LOT", slug: "food" },
  { pattern: "FRESH THYME", slug: "food" },
  { pattern: "GELSONS", slug: "food" },
  { pattern: "BRISTOL FARMS", slug: "food" },
  { pattern: "CASH AND CARRY", slug: "food" },
  { pattern: "US FOODS", slug: "food" },
  { pattern: "FOODMAXX", slug: "food" },
  { pattern: "LUCKY SUPERMARKET", slug: "food" },
  { pattern: "CARDENAS", slug: "food" },
  { pattern: "NORTHGATE MARKET", slug: "food" },
  { pattern: "VALLARTA SUPERMERCADO", slug: "food" },
  { pattern: "PATEL BROTHERS", slug: "food" },
  { pattern: "RALEYS", slug: "food" },
  { pattern: "NUGGET MARKET", slug: "food" },
  { pattern: "FAREWAY", slug: "food" },
  { pattern: "BROOKSHIRE", slug: "food" },
  { pattern: "CUB FOODS", slug: "food" },
  { pattern: "WEIS MARKETS", slug: "food" },
  { pattern: "GIANT FOOD", slug: "food" },
  { pattern: "STOP AND SHOP", slug: "food" },
  { pattern: "HANNAFORD", slug: "food" },
  { pattern: "SHAWS", slug: "food" },
  { pattern: "STAR MARKET", slug: "food" },
  { pattern: "FOOD BAZAAR", slug: "food" },
  { pattern: "KEY FOOD", slug: "food" },
  { pattern: "FOODTOWN", slug: "food" },
  { pattern: "ASSOCIATED SUPERMARKET", slug: "food" },
  { pattern: "NATURAL GROCERS", slug: "food" },
  { pattern: "EARTH FARE", slug: "food" },
  { pattern: "NEW SEASONS", slug: "food" },
  { pattern: "MET MARKET", slug: "food" },
  { pattern: "PCC COMMUNITY", slug: "food" },
  { pattern: "CENTRAL MARKET", slug: "food" },
  { pattern: "HEB ", slug: "food" },
  { pattern: "SCHNUCKS", slug: "food" },
  { pattern: "DIERBERGS", slug: "food" },
  { pattern: "HYVEE", slug: "food" },
  { pattern: "WOODMANS", slug: "food" },
  { pattern: "FESTIVAL FOODS", slug: "food" },
  { pattern: "PICK N SAVE", slug: "food" },
  { pattern: "SENDIKS", slug: "food" },
  { pattern: "MARIANOS", slug: "food" },
  { pattern: "QFC ", slug: "food" },
  { pattern: "SMITHS ", slug: "food" },
  { pattern: "FOODS CO", slug: "food" },
  { pattern: "SMART FOOD", slug: "food" },
  { pattern: "GROCERY OUTLET", slug: "food" },
  { pattern: "ALDI ", slug: "food" },
  { pattern: "LIDL ", slug: "food" },
  { pattern: "VONS ", slug: "food" },
  { pattern: "SAM'S CLUB", slug: "food", weak: true },
  { pattern: "COSTCO WHOLESALE", slug: "food", weak: true },
  { pattern: "BJ'S WHOLESALE", slug: "food", weak: true },
  { pattern: "MCDONALDS", slug: "dining" },
  { pattern: "MCDONALD'S", slug: "dining" },
  { pattern: "WENDYS", slug: "dining" },
  { pattern: "WENDY'S", slug: "dining" },
  { pattern: "CHICK-FIL-A", slug: "dining" },
  { pattern: "CHICK FIL A", slug: "dining" },
  { pattern: "ARBYS", slug: "dining" },
  { pattern: "ARBY'S", slug: "dining" },
  { pattern: "CULVERS", slug: "dining" },
  { pattern: "CULVER'S", slug: "dining" },
  { pattern: "WHITE CASTLE", slug: "dining" },
  { pattern: "PANERA BREAD", slug: "dining" },
  { pattern: "MOES SOUTHWEST", slug: "dining" },
  { pattern: "CHILIS", slug: "dining" },
  { pattern: "TEXAS ROADHOUSE", slug: "dining" },
  { pattern: "OUTBACK STEAK", slug: "dining" },
  { pattern: "RED ROBIN", slug: "dining" },
  { pattern: "DENNYS", slug: "dining" },
  { pattern: "DENNY'S", slug: "dining" },
  { pattern: "IHOP ", slug: "dining" },
  { pattern: "WAFFLE HOUSE", slug: "dining" },
  { pattern: "DOMINO'S", slug: "dining" },
  { pattern: "PAPA JOHNS", slug: "dining" },
  { pattern: "LITTLE CAESARS", slug: "dining" },
  { pattern: "PHO HOA", slug: "dining" },
  { pattern: "BUFFALO WILD WINGS", slug: "dining" },
  { pattern: "ZAXBYS", slug: "dining" },
  { pattern: "NOODLES AND COMPANY", slug: "dining" },
  { pattern: "PEETS COFFEE", slug: "dining" },
  { pattern: "CARIBOU COFFEE", slug: "dining" },
  { pattern: "TIM HORTONS", slug: "dining" },
  { pattern: "BIGGBY", slug: "dining" },
  { pattern: "POSTMATES", slug: "dining" },
  { pattern: "SEAMLESS", slug: "dining" },
  { pattern: "TOASTTAB", slug: "dining" },
  { pattern: "CAVIAR ", slug: "dining" },
  { pattern: "WAWA ", slug: "gas" },
  { pattern: "PILOT TRAVEL", slug: "gas" },
  { pattern: "LOVES TRAVEL", slug: "gas" },
  { pattern: "LOVE'S", slug: "gas" },
  { pattern: "BUCCEES", slug: "gas" },
  { pattern: "BUC-EE", slug: "gas" },
  { pattern: "MURPHY USA", slug: "gas" },
  { pattern: "CASEY'S", slug: "gas" },
  { pattern: "MOBIL ", slug: "gas" },
  { pattern: "MARATHON PETRO", slug: "gas" },
  { pattern: "TESLA SUPERCHARGER", slug: "transport" },
  { pattern: "CHARGEPOINT", slug: "transport" },
  { pattern: "EVGO ", slug: "transport" },
  { pattern: "ELECTRIFY AMERICA", slug: "transport" },
  { pattern: "BLINK CHARGING", slug: "transport" },
  { pattern: "PARKWHIZ", slug: "transport" },
  { pattern: "SPOTHERO", slug: "transport" },
  { pattern: "LAZ PARKING", slug: "transport" },
  { pattern: "IMPARK", slug: "transport" },
  { pattern: "EZ PASS", slug: "transport" },
  { pattern: "CLIPPER", slug: "transport" },
  { pattern: "VENTRA", slug: "transport" },
  { pattern: "METROCARD", slug: "transport" },
  { pattern: "UBER TRIP", slug: "transport" },
  { pattern: "LYFT RIDE", slug: "transport" },
  { pattern: "MIDAS ", slug: "transport" },
  { pattern: "FIRESTONE", slug: "transport" },
  { pattern: "O'REILLY AUTO", slug: "transport" },
  { pattern: "ADVANCE AUTO", slug: "transport" },
  { pattern: "NAPA AUTO", slug: "transport" },
  { pattern: "PROGRESSIVE INS", slug: "transport" },
  { pattern: "USAA ", slug: "transport" },
  { pattern: "LEMONADE INS", slug: "housing" },
  { pattern: "STATE FARM RENT", slug: "housing" },
  { pattern: "GEORGIA POWER", slug: "utilities" },
  { pattern: "SOUTHERN CALIFORNIA EDISON", slug: "utilities" },
  { pattern: "SCE ", slug: "utilities" },
  { pattern: "SRP POWER", slug: "utilities" },
  { pattern: "AEP ", slug: "utilities" },
  { pattern: "PECO ", slug: "utilities" },
  { pattern: "NICOR GAS", slug: "utilities" },
  { pattern: "SOCALGAS", slug: "utilities" },
  { pattern: "ATMOS ENERGY", slug: "utilities" },
  { pattern: "AMERICAN WATER", slug: "utilities" },
  { pattern: "COX COMMUNICATIONS", slug: "utilities" },
  { pattern: "METRO BY T-MOBILE", slug: "utilities" },
  { pattern: "VISIBLE ", slug: "utilities" },
  { pattern: "HBO MAX", slug: "subscriptions" },
  { pattern: "MICROSOFT", slug: "subscriptions" },
  { pattern: "GOOGLE STORAGE", slug: "subscriptions" },
  { pattern: "NOTION LABS", slug: "subscriptions" },
  { pattern: "ANYTIME FITNESS", slug: "health" },
  { pattern: "ORANGETHEORY", slug: "health" },
  { pattern: "EQUINOX", slug: "health" },
  { pattern: "24 HOUR FITNESS", slug: "health" },
  { pattern: "CVS/PHARMACY", slug: "health" },
  { pattern: "CVS PHARMACY", slug: "health" },
  { pattern: "ASPEN DENTAL", slug: "health" },
  { pattern: "LENSCRAFTERS", slug: "health" },
  { pattern: "WARBY PARKER", slug: "health" },
  { pattern: "BETTERHELP", slug: "health" },
  { pattern: "VCA ANIMAL", slug: "pets" },
  { pattern: "BRIGHT HORIZONS", slug: "childcare" },
  { pattern: "GODDARD SCHOOL", slug: "childcare" },
  { pattern: "PRIMROSE SCHOOL", slug: "childcare" },
  { pattern: "LA PETITE", slug: "childcare" },
  { pattern: "NELNET", slug: "debt" },
  { pattern: "FEDLOAN", slug: "debt" },
  { pattern: "GREAT LAKES", slug: "debt" },
  { pattern: "SALLIE MAE", slug: "debt" },
  { pattern: "ASHLEY FURNITURE", slug: "personal" },
  { pattern: "APPLE STORE", slug: "personal" },
  { pattern: "MICRO CENTER", slug: "personal" },
  { pattern: "GAMESTOP", slug: "personal" },
  { pattern: "MACYS", slug: "personal" },
  { pattern: "MACY'S", slug: "personal" },
  { pattern: "KOHLS", slug: "personal" },
  { pattern: "GAP ", slug: "personal" },
  { pattern: "H&M", slug: "personal" },
  { pattern: "BURLINGTON STORES", slug: "personal" },
  { pattern: "ULTA ", slug: "personal" },
  { pattern: "USPS", slug: "personal" },
  { pattern: "UPS STORE", slug: "personal" },
  { pattern: "FEDEX", slug: "personal" },
  { pattern: "UNITED AIRLINES", slug: "travel" },
  { pattern: "AMERICAN AIRLINES", slug: "travel" },
  { pattern: "SOUTHWEST AIR", slug: "travel" },
  { pattern: "SPIRIT AIR", slug: "travel" },
  { pattern: "HERTZ", slug: "travel" },
  { pattern: "ENTERPRISE RENT", slug: "travel" },
  { pattern: "NATIONAL CAR", slug: "travel" },
  { pattern: "AVIS ", slug: "travel" },
  { pattern: "BUDGET RENT", slug: "travel" },
  { pattern: "RED CROSS", slug: "giving" },
  { pattern: "GOODWILL", slug: "giving" },
  { pattern: "UNITED WAY", slug: "giving" },
  { pattern: "SALVATION ARMY", slug: "giving" },
  { pattern: "GO FUND ME", slug: "giving" },
  { pattern: "IRS ", slug: "other" },
  { pattern: "US TREASURY", slug: "other" },
  { pattern: "FRANCHISE TAX", slug: "other" },
  { pattern: "DMV ", slug: "other" },
  { pattern: "DEPARTMENT OF MOTOR", slug: "other" },
  { pattern: "OVERDRAFT FEE", slug: "other" },
  { pattern: "FOREIGN TRANSACTION FEE", slug: "other" },
  { pattern: "AMEX EPAYMENT", slug: "transfers-out" },
  { pattern: "CAPITAL ONE MOBILE PMT", slug: "transfers-out" },
  { pattern: "CITI CARD PAYMENT", slug: "transfers-out" },
  { pattern: "DISCOVER E-PAYMENT", slug: "transfers-out" },
  { pattern: "PAYMENT THANK YOU", slug: "transfers-out" },
  { pattern: "SPROUTS FARMERS", slug: "food" },
  { pattern: "KROGER FUEL", slug: "food" },
  { pattern: "ALBERTSON", slug: "food" },
  { pattern: "WINN-DIXIE", slug: "food" },
  { pattern: "PIGGLY", slug: "food" },
  { pattern: "FOOD LION STORE", slug: "food" },
  { pattern: "MARKET STREET", slug: "food" },
  { pattern: "UNITED SUPERMARKET", slug: "food" },
  { pattern: "LOWES FOODS", slug: "food" },
  { pattern: "HARPS FOOD", slug: "food" },
  { pattern: "TOPS FRIENDLY", slug: "food" },
  { pattern: "ACME MARKETS", slug: "food" },
  { pattern: "WEIS ", slug: "food" },
  { pattern: "STATER BROTHERS", slug: "food" },
  { pattern: "SMART FINAL", slug: "food" },
  { pattern: "POPEYE", slug: "dining" },
  { pattern: "KFC ", slug: "dining" },
  { pattern: "LONGHORN STEAK", slug: "dining" },
  { pattern: "APPLEBEE", slug: "dining" },
  { pattern: "TGI FRIDAY", slug: "dining" },
  { pattern: "PF CHANG", slug: "dining" },
  { pattern: "CHEesecake FACTORY", slug: "dining" },
  { pattern: "CHEESECAKE FACTORY", slug: "dining" },
  { pattern: "BJ'S RESTAURANT", slug: "dining" },
  { pattern: "BONEFISH", slug: "dining" },
  { pattern: "CARRABBA", slug: "dining" },
  { pattern: "PORTILLOS", slug: "dining" },
  { pattern: "JIMMY JOHNS", slug: "dining" },
  { pattern: "JERSEY MIKES", slug: "dining" },
  { pattern: "FIREHOUSE SUBS", slug: "dining" },
  { pattern: "SUBWAY ", slug: "dining" },
  { pattern: "CAVA ", slug: "dining" },
  { pattern: "SHAKESHACK", slug: "dining" },
  { pattern: "CANES ", slug: "dining" },
  { pattern: "RACETRACK", slug: "gas" },
  { pattern: "KWIK TRIP", slug: "gas" },
  { pattern: "76 GAS", slug: "gas" },
  { pattern: "TESLA SUPER", slug: "transport" },
  { pattern: "CHARGE POINT", slug: "transport" },
  { pattern: "EVGO CHARGING", slug: "transport" },
  { pattern: "PARKMOBILE", slug: "transport" },
  { pattern: "PAYBYPHONE", slug: "transport" },
  { pattern: "LAZ PARK", slug: "transport" },
  { pattern: "UBER ", slug: "transport" },
  { pattern: "LYFT ", slug: "transport" },
  { pattern: "BIRD SCOOTER", slug: "transport" },
  { pattern: "LIME SCOOTER", slug: "transport" },
  { pattern: "VIA TRANSPORT", slug: "transport" },
  { pattern: "MTA ", slug: "transport" },
  { pattern: "WMATA", slug: "transport" },
  { pattern: "BART ", slug: "transport" },
  { pattern: "CALTRAIN", slug: "transport" },
  { pattern: "NJ TRANSIT", slug: "transport" },
  { pattern: "AMTRAK", slug: "transport" },
  { pattern: "DIRECTV", slug: "utilities" },
  { pattern: "DISH NETWORK", slug: "utilities" },
  { pattern: "ASTOUND", slug: "utilities" },
  { pattern: "FRONTIER COMMUN", slug: "utilities" },
  { pattern: "WOW INTERNET", slug: "utilities" },
  { pattern: "GOOGLE FIBER", slug: "utilities" },
  { pattern: "CONSUMERS ENERGY", slug: "utilities" },
  { pattern: "DTE ENERGY", slug: "utilities" },
  { pattern: "NATIONAL FUEL", slug: "utilities" },
  { pattern: "COLUMBIA GAS", slug: "utilities" },
  { pattern: "SPIRE GAS", slug: "utilities" },
  { pattern: "SW GAS", slug: "utilities" },
  { pattern: "WALGREEN", slug: "health" },
  { pattern: "RITEAID", slug: "health" },
  { pattern: "OPTUM", slug: "health" },
  { pattern: "ANTHEM", slug: "health" },
  { pattern: "OSCAR HEALTH", slug: "health" },
  { pattern: "MOLINA", slug: "health" },
  { pattern: "CENTENE", slug: "health" },
  { pattern: "DENTAL OFFICE", slug: "health" },
  { pattern: "VISIONWORKS", slug: "health" },
  { pattern: "MYEYEDR", slug: "health" },
  { pattern: "HEADSPACE", slug: "health" },
  { pattern: "TALKSPACE", slug: "health" },
  { pattern: "WSJ ", slug: "subscriptions" },
  { pattern: "WASHINGTON POST", slug: "subscriptions" },
  { pattern: "KINDLE", slug: "subscriptions" },
  { pattern: "NOTION ", slug: "subscriptions" },
  { pattern: "FIGMA", slug: "subscriptions" },
  { pattern: "SPOTIFY USA", slug: "subscriptions" },
  { pattern: "NETFLIX.COM", slug: "subscriptions" },
  { pattern: "HULU.COM", slug: "subscriptions" },
  { pattern: "PEACOCKTV", slug: "subscriptions" },
  { pattern: "TARGET.COM", slug: "personal", weak: true },
  { pattern: "AMAZON.COM", slug: "personal", weak: true },
  { pattern: "AMZN MKTP", slug: "personal", weak: true },
  { pattern: "ETSY.COM", slug: "personal" },
  { pattern: "WALMART.COM", slug: "personal", weak: true },
  { pattern: "COSTCO.COM", slug: "personal", weak: true },
  { pattern: "DSW ", slug: "personal" },
  { pattern: "FOOT LOCKER", slug: "personal" },
  { pattern: "BATH AND BODY", slug: "personal" },
  { pattern: "BATH & BODY", slug: "personal" },
  { pattern: "SALLY BEAUTY", slug: "personal" },
  { pattern: "BARBERSHOP", slug: "personal" },
  { pattern: "CHEWY.COM", slug: "pets" },
  { pattern: "PET SUPPLIES", slug: "pets" },
  { pattern: "VET CLINIC", slug: "pets" },
  { pattern: "AFTER SCHOOL", slug: "childcare" },
  { pattern: "SEZZLE", slug: "debt" },
  { pattern: "EARNEST", slug: "debt" },
  { pattern: "SOFI ", slug: "debt" },
  { pattern: "RENT PAYMENT", slug: "housing" },
  { pattern: "MORTGAGE PAYMENT", slug: "housing" },
  { pattern: "HOTELS.COM", slug: "travel" },
  { pattern: "SOUTHWEST.COM", slug: "travel" },
  { pattern: "DELTA.COM", slug: "travel" },
  { pattern: "UNITED.COM", slug: "travel" },
  { pattern: "MAINTENANCE FEE", slug: "other" },
  { pattern: "CASHIERS CHECK", slug: "other" },
  { pattern: "AUTOPAY PAYMENT", slug: "transfers-out" },
  { pattern: "ONLINE PAYMENT THANK YOU", slug: "transfers-out" },
  { pattern: "PAYPAL", slug: "side-work" },
];

const SORTED = [...KEYWORD_RULES].sort((a, b) => b.pattern.length - a.pattern.length);

export function matchKeyword(text: string): { slug: string; pattern: string; weak: boolean } | null {
  const hay = ` ${String(text || "").toUpperCase()} `;
  for (const rule of SORTED) {
    if (hay.includes(rule.pattern.toUpperCase())) {
      return { slug: rule.slug, pattern: rule.pattern, weak: rule.weak === true };
    }
  }
  return null;
}

export function matchKeywordSlug(text: string): string | null {
  return matchKeyword(text)?.slug ?? null;
}

export const SLUG_FALLBACKS: Record<string, string[]> = {
  dining: ["food"],
  subscriptions: ["entertainment", "personal"],
  pets: ["personal"],
  travel: ["entertainment", "other"],
  "transfers-out": ["other"],
  "other-income": ["transfers-in"],
  groceries: ["food"],
};
